package mealplanner;

import java.sql.Connection;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

public class theGui extends javax.swing.JFrame {
    String dayHome;

    /**
     * Creates new form theGui
     */
    public theGui() {
        initComponents();
        dayHome = "Sunday";
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPane1 = new javax.swing.JDesktopPane();
        jSpinner1 = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        SearchR1 = new javax.swing.JButton();
        jScrollPane18 = new javax.swing.JScrollPane();
        searchList1 = new javax.swing.JList();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jTextField1 = new javax.swing.JTextField();
        buttonGroup2 = new javax.swing.ButtonGroup();
        title = new javax.swing.JLabel();
        App = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        Sunday1 = new javax.swing.JButton();
        Monday1 = new javax.swing.JButton();
        Tuesday1 = new javax.swing.JButton();
        Wednesday1 = new javax.swing.JButton();
        Thursday1 = new javax.swing.JButton();
        Friday1 = new javax.swing.JButton();
        Saturday1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        mealsB = new javax.swing.JList();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        mealsL = new javax.swing.JList();
        l3 = new javax.swing.JLabel();
        jScrollPane10 = new javax.swing.JScrollPane();
        mealsD = new javax.swing.JList();
        jScrollPane11 = new javax.swing.JScrollPane();
        ingredients = new javax.swing.JTextPane();
        jLabel9 = new javax.swing.JLabel();
        fridge = new javax.swing.JPanel();
        jScrollPane12 = new javax.swing.JScrollPane();
        curFood = new javax.swing.JList();
        jScrollPane15 = new javax.swing.JScrollPane();
        foodFacts = new javax.swing.JTextPane();
        addF = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        removeF = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane23 = new javax.swing.JScrollPane();
        foodlist1 = new javax.swing.JList();
        shopList = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        foodneeded = new javax.swing.JList();
        jScrollPane13 = new javax.swing.JScrollPane();
        foodInfo = new javax.swing.JTextPane();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        mealPlan = new javax.swing.JPanel();
        l4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        mealsB1 = new javax.swing.JList();
        jScrollPane16 = new javax.swing.JScrollPane();
        mealsL1 = new javax.swing.JList();
        jScrollPane17 = new javax.swing.JScrollPane();
        mealsD1 = new javax.swing.JList();
        jScrollPane7 = new javax.swing.JScrollPane();
        weekList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        recList = new javax.swing.JList();
        breakfast = new javax.swing.JToggleButton();
        lunch = new javax.swing.JToggleButton();
        dnd = new javax.swing.JToggleButton();
        Sunday = new javax.swing.JToggleButton();
        Monday = new javax.swing.JToggleButton();
        Tuesday = new javax.swing.JToggleButton();
        Thursday = new javax.swing.JToggleButton();
        Wednesday = new javax.swing.JToggleButton();
        Friday = new javax.swing.JToggleButton();
        Saturday = new javax.swing.JToggleButton();
        removeR = new javax.swing.JButton();
        addR = new javax.swing.JButton();
        jScrollPane14 = new javax.swing.JScrollPane();
        searchList = new javax.swing.JList();
        SearchR = new javax.swing.JButton();
        Category = new javax.swing.JRadioButton();
        Ingredients = new javax.swing.JRadioButton();
        cookbook = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        listCategory = new javax.swing.JList();
        jScrollPane4 = new javax.swing.JScrollPane();
        Rlist = new javax.swing.JList();
        jScrollPane6 = new javax.swing.JScrollPane();
        Flist = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        EditRecipe = new javax.swing.JToggleButton();
        Update = new javax.swing.JButton();
        SearchR2 = new javax.swing.JButton();
        jScrollPane19 = new javax.swing.JScrollPane();
        searchList2 = new javax.swing.JList();
        IngredientC = new javax.swing.JRadioButton();
        CategoryC = new javax.swing.JRadioButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Rname = new javax.swing.JTextField();
        jScrollPane20 = new javax.swing.JScrollPane();
        Inlist = new javax.swing.JList();
        jScrollPane21 = new javax.swing.JScrollPane();
        listingredient = new javax.swing.JList();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane22 = new javax.swing.JScrollPane();
        Instructions = new javax.swing.JTextArea();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        SearchR1.setText("Search");

        searchList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane18.setViewportView(searchList1);

        jRadioButton3.setText("ingredients");

        jRadioButton4.setText("Category");

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jTextField1.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        title.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("My Meal Planner");

        App.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                AppStateChanged(evt);
            }
        });

        Sunday1.setText("Sunday");
        Sunday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sunday1ActionPerformed(evt);
            }
        });

        Monday1.setText("Monday");
        Monday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Monday1ActionPerformed(evt);
            }
        });

        Tuesday1.setText("Tuesday");
        Tuesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tuesday1ActionPerformed(evt);
            }
        });

        Wednesday1.setText("Wednesday");
        Wednesday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Wednesday1ActionPerformed(evt);
            }
        });

        Thursday1.setText("Thursday");
        Thursday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Thursday1ActionPerformed(evt);
            }
        });

        Friday1.setText("Friday");
        Friday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Friday1ActionPerformed(evt);
            }
        });

        Saturday1.setText("Saturday");
        Saturday1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Saturday1ActionPerformed(evt);
            }
        });

        mealsB.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "recipe name 1", "recipe name 2", "recipe name 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        mealsB.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(mealsB);

        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("Breakfast");

        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("Lunch");

        mealsL.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "recipe name 1", "recipe name 2", "recipe name 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        mealsL.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane9.setViewportView(mealsL);

        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("Dinner/Dessert");

        mealsD.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "recipe name 1", "recipe name 2", "recipe name 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        mealsD.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        mealsD.setToolTipText("");
        jScrollPane10.setViewportView(mealsD);

        ingredients.setEditable(false);
        jScrollPane11.setViewportView(ingredients);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Ingredients");

        javax.swing.GroupLayout homeLayout = new javax.swing.GroupLayout(home);
        home.setLayout(homeLayout);
        homeLayout.setHorizontalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Sunday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Wednesday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Tuesday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Monday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Thursday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Friday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Saturday1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane9)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane10)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane11)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        homeLayout.setVerticalGroup(
            homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homeLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(homeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(homeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l3, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane10, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(151, 151, 151))
            .addGroup(homeLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(Sunday1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Monday1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Tuesday1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Wednesday1)
                .addGap(12, 12, 12)
                .addComponent(Thursday1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Friday1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Saturday1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        App.addTab("Home", home);

        curFood.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        curFood.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        curFood.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                curFoodFocusGained(evt);
            }
        });
        jScrollPane12.setViewportView(curFood);

        jScrollPane15.setViewportView(foodFacts);

        addF.setText("Add Food");

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Food in Stock");

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nutrition Facts");

        removeF.setText("Remove Food");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Food");
        jLabel14.setToolTipText("");

        foodlist1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        foodlist1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                foodlist1FocusGained(evt);
            }
        });
        jScrollPane23.setViewportView(foodlist1);

        javax.swing.GroupLayout fridgeLayout = new javax.swing.GroupLayout(fridge);
        fridge.setLayout(fridgeLayout);
        fridgeLayout.setHorizontalGroup(
            fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fridgeLayout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(fridgeLayout.createSequentialGroup()
                        .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(fridgeLayout.createSequentialGroup()
                                .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jScrollPane12)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 169, Short.MAX_VALUE))
                                .addGap(44, 44, 44))
                            .addGroup(fridgeLayout.createSequentialGroup()
                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(95, 95, 95)))
                        .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane15)
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(fridgeLayout.createSequentialGroup()
                        .addComponent(jScrollPane23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addF)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeF)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        fridgeLayout.setVerticalGroup(
            fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, fridgeLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane12, javax.swing.GroupLayout.DEFAULT_SIZE, 232, Short.MAX_VALUE)
                    .addComponent(jScrollPane15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(fridgeLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(fridgeLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addGroup(fridgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(addF)
                            .addComponent(removeF))))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        App.addTab("Fridge", fridge);

        foodneeded.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(foodneeded);

        jScrollPane13.setViewportView(foodInfo);

        jButton1.setText("Update List");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Nutrition Facts");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Food Needed");

        javax.swing.GroupLayout shopListLayout = new javax.swing.GroupLayout(shopList);
        shopList.setLayout(shopListLayout);
        shopListLayout.setHorizontalGroup(
            shopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(shopListLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(26, 26, 26))
            .addGroup(shopListLayout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(shopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane5)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(shopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        shopListLayout.setVerticalGroup(
            shopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, shopListLayout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(shopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(shopListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane13, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jButton1))
        );

        App.addTab("Shoppinglist", shopList);

        l4.setText("Recipes");

        mealsB1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "recipe name 1", "recipe name 2", "recipe name 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(mealsB1);

        mealsL1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "recipe name 1", "recipe name 2", "recipe name 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane16.setViewportView(mealsL1);

        mealsD1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "recipe name 1", "recipe name 2", "recipe name 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane17.setViewportView(mealsD1);

        weekList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Current week", "previous week 1", "previous week 2", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane7.setViewportView(weekList);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Weekly Plans");

        recList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane8.setViewportView(recList);

        breakfast.setText("Breakfast");

        lunch.setText("Lunch");

        dnd.setText("Dinner/Dessert");
        dnd.setActionCommand("DinnerDessert");

        Sunday.setText("Sunday");

        Monday.setText("Monday");

        Tuesday.setText("Tuesday");

        Thursday.setText("Thursday");

        Wednesday.setText("Wednesday");

        Friday.setText("Friday");

        Saturday.setText("Saturday");

        removeR.setText("Remove Recipe");

        addR.setText("Add Recipe");

        searchList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane14.setViewportView(searchList);

        SearchR.setText("Search");

        Category.setText("Category");

        Ingredients.setText("Ingredients");

        javax.swing.GroupLayout mealPlanLayout = new javax.swing.GroupLayout(mealPlan);
        mealPlan.setLayout(mealPlanLayout);
        mealPlanLayout.setHorizontalGroup(
            mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealPlanLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(removeR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addR)
                .addGap(33, 33, 33))
            .addGroup(mealPlanLayout.createSequentialGroup()
                .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mealPlanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Category)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Ingredients)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, mealPlanLayout.createSequentialGroup()
                            .addGap(14, 14, 14)
                            .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(mealPlanLayout.createSequentialGroup()
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Sunday)
                                        .addComponent(Monday)
                                        .addComponent(Tuesday)
                                        .addComponent(Thursday)
                                        .addComponent(Wednesday)
                                        .addComponent(Friday)
                                        .addComponent(Saturday))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(dnd, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(breakfast, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane16, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane17, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lunch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(jLabel4))
                            .addGap(27, 27, 27)
                            .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(l4, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(mealPlanLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(SearchR))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        mealPlanLayout.setVerticalGroup(
            mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mealPlanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Category)
                        .addComponent(Ingredients)))
                .addGap(7, 7, 7)
                .addComponent(SearchR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(l4))
                .addGap(31, 31, 31)
                .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(mealPlanLayout.createSequentialGroup()
                        .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(breakfast)
                            .addComponent(Sunday))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(mealPlanLayout.createSequentialGroup()
                                .addComponent(Monday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Tuesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Wednesday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Thursday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Friday)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Saturday))
                            .addGroup(mealPlanLayout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lunch)
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dnd)
                                .addGap(5, 5, 5)
                                .addComponent(jScrollPane17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(mealPlanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removeR)
                    .addComponent(addR)))
        );

        App.addTab("Meal Planning", mealPlan);

        listCategory.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listCategory);

        Rlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(Rlist);

        Flist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane6.setViewportView(Flist);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Recipies");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Current Ingredients");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Food");

        EditRecipe.setText("Add Ingredient");

        Update.setText("Update Recipe");

        SearchR2.setText("Search");

        searchList2.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane19.setViewportView(searchList2);

        IngredientC.setText("Ingredients");

        CategoryC.setText("Category");

        jButton3.setText("Remove ingredient");

        jButton4.setText("Reset");

        jButton5.setText("Add Recipe");

        Rname.setText("Recipe Name");

        Inlist.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane20.setViewportView(Inlist);

        listingredient.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane21.setViewportView(listingredient);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Ingredients");

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Category");

        Instructions.setColumns(20);
        Instructions.setRows(5);
        jScrollPane22.setViewportView(Instructions);

        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Instructions");

        jLabel13.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel13.setText("Add a Recipe");

        javax.swing.GroupLayout cookbookLayout = new javax.swing.GroupLayout(cookbook);
        cookbook.setLayout(cookbookLayout);
        cookbookLayout.setHorizontalGroup(
            cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookbookLayout.createSequentialGroup()
                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cookbookLayout.createSequentialGroup()
                        .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(cookbookLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14))
                            .addGroup(cookbookLayout.createSequentialGroup()
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane20, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane6)))
                    .addGroup(cookbookLayout.createSequentialGroup()
                        .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(cookbookLayout.createSequentialGroup()
                                .addGap(202, 202, 202)
                                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(cookbookLayout.createSequentialGroup()
                                        .addComponent(CategoryC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(IngredientC)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(SearchR2)))
                            .addGroup(cookbookLayout.createSequentialGroup()
                                .addGap(416, 416, 416)
                                .addComponent(jButton5))
                            .addGroup(cookbookLayout.createSequentialGroup()
                                .addComponent(Rname, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane21)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13))
                                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(cookbookLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(cookbookLayout.createSequentialGroup()
                                        .addGap(80, 80, 80)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(cookbookLayout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jButton4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditRecipe)
                                .addGap(22, 22, 22)
                                .addComponent(Update)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        cookbookLayout.setVerticalGroup(
            cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cookbookLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(CategoryC)
                        .addComponent(IngredientC))
                    .addComponent(jScrollPane19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SearchR2)
                .addGap(21, 21, 21)
                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(9, 9, 9)
                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6)
                    .addComponent(jScrollPane20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Update)
                    .addComponent(EditRecipe)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(cookbookLayout.createSequentialGroup()
                        .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Rname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5))
                    .addGroup(cookbookLayout.createSequentialGroup()
                        .addGroup(cookbookLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane21, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );

        App.addTab("Cookbook", cookbook);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(App)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(214, 214, 214)
                .addComponent(title, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(App, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        App.getAccessibleContext().setAccessibleName("Current meal plan");

        pack();
    }// </editor-fold>//GEN-END:initComponents

//Home Tab
    private void Sunday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sunday1ActionPerformed
        // TODO add your handling code here:
        dayHome = "Sunday";
        int select = 0, rec = 0, ing = 0;
        String recipeName = "";
        String[] listDataR;
        String[] listDataI;
        
        //empties selection from the day's recipes
        mealsB.clearSelection();
        mealsL.clearSelection();
        mealsD.clearSelection();
        //pass "dayHome" in the query call
        
            //store query call in a string array listDataR
            rec = 5;        //grab total number of recipes and store them in rec
            listDataR = new String[rec];
            
            //set mealsB list with breakfast recipes from listDataR
            mealsB.setListData(listDataR);
            if(mealsB.hasFocus()){
                select = mealsB.getSelectedIndex();
                recipeName = listDataR[select];
            
                //grab recipe ingredients and store in listDataI
                ing = 5;        //grab total number of ingredoents and store them in ing
                listDataI = new String[ing];

                //clear ingredients text
                ingredients.setText("");
                //add list of the selected recipes to the ingredients pane
                for(int i = 0; i < listDataI.length; i++){
                    ingredients.setText(ingredients.getText()+"/n"+listDataI[i]);
                }
            }
        //set mealsL list with lunch recipes
        
        //set mealsD list with dinner/dessert recipes
        
    }//GEN-LAST:event_Sunday1ActionPerformed

    private void Monday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Monday1ActionPerformed
        // TODO add your handling code here:
        dayHome = "Monday";
    }//GEN-LAST:event_Monday1ActionPerformed

    private void Tuesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tuesday1ActionPerformed
        // TODO add your handling code here:
        dayHome = "Tuesday";
    }//GEN-LAST:event_Tuesday1ActionPerformed

    private void Wednesday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Wednesday1ActionPerformed
        // TODO add your handling code here:
        dayHome = "Wednesday";
    }//GEN-LAST:event_Wednesday1ActionPerformed

    private void Thursday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Thursday1ActionPerformed
        // TODO add your handling code here:
        dayHome = "Thursday";
    }//GEN-LAST:event_Thursday1ActionPerformed

    private void Friday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Friday1ActionPerformed
        // TODO add your handling code here:
        dayHome = "Friday";
    }//GEN-LAST:event_Friday1ActionPerformed

    private void Saturday1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Saturday1ActionPerformed
        // TODO add your handling code here:
        dayHome = "Saturday";
    }//GEN-LAST:event_Saturday1ActionPerformed

//Fridge page
    private void curFoodFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_curFoodFocusGained
        // TODO add your handling code here:
        System.out.println("HIIIIIIIIII");
        int select = 0, n = 0;
        String foodName = "", nutr = "";
        
        //grab selected food name's nutrition facts
        select = curFood.getSelectedIndex();
        
        //query call foodName = curFood[select];
        
        //store query call in a nutr
        nutr = "facts";
        foodFacts.setText(nutr);
        
    }//GEN-LAST:event_curFoodFocusGained

//fridge page
    private void foodlist1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_foodlist1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_foodlist1FocusGained

    private void AppStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_AppStateChanged
        // TODO add your handling code here:
        
        int select = 0, rec = 0, ffood = 0, food2 = 0 , ing = 0, cat = 0;
        String foodName = "";
        String[] listDataF;     //string of food names from query
        String[] listDataC;     //string of food names from query
        String[] listDataR;     //list of recipes
        String[] listDataI;     //list of recipe ingredients
        String[] foodN = {};    //food list for the shopping list page
        String[] foodH = {};    //food in the fridge
        
        int page = App.getSelectedIndex();
        switch(page){
            case 0: //home
                
                //query call for breakfast day is Sunday
                
                rec = 5;        //grab total number of recipes and store them in rec
                listDataR = new String[rec];
                //set mealsB list with breakfast recipes from listDataR
                mealsB.setListData(listDataR);
                
                //query call for lunch day is Sunday
                
                rec = 5;        //grab total number of recipes and store them in rec
                listDataR = new String[rec];
                //set mealsB list with breakfast recipes from listDataR
                mealsL.setListData(listDataR);
                
                //query call for dinner day is Sunday
                
                rec = 5;        //grab total number of recipes and store them in rec
                listDataR = new String[rec];
                //set mealsB list with breakfast recipes from listDataR
                mealsD.setListData(listDataR);
                
                break;
            case 1: //fridge
                //store query call in a string array listDataF
                food2 = 5;        //grab total number of foods and store them in food2
                listDataF = new String[food2];
                foodlist1.setListData(listDataF);   //food list for them to add to their fridge
                
                curFood.setListData(foodH);         //populate contents of the  fridge
                
                break;
            case 2: //shopping list
                //compare fridge and recipe ingredients to populate foodneeded
                foodneeded.setListData(foodN);
                break;
            case 3: // meal planning
                // populate the weeks list column
                
                //populate recList
                rec = 5;        //grab total number of recipes and store them in rec
                listDataR = new String[rec];
                recList.setListData(listDataR);
                
                break;
            case 4: //cookbook
                //populate recList
                rec = 5;        //grab total number of recipes and store them in rec
                listDataR = new String[rec];
                Rlist.setListData(listDataR);
                
                //populate Inlist
                ing = 5;        //grab total number of recipe ingredients and store them in ing
                listDataI = new String[ing];
                Inlist.setListData(listDataI);
                
                //populate FList
                ffood = 5;        //grab total number of Food and store them in rec
                foodH = new String[ffood];
                Flist.setListData(foodH);
                //populate listingredient with food for add recicpe section
                listingredient.setListData(foodH);
                
                //populate listCategory
                cat = 5;        //grab total number of categories in the food section and store them in 
                listDataC = new String[cat];
                listCategory.setListData(listDataC);
                
                break;    
            default:
                break;
        }
    }//GEN-LAST:event_AppStateChanged

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(theGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(theGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(theGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(theGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new theGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane App;
    private javax.swing.JRadioButton Category;
    private javax.swing.JRadioButton CategoryC;
    private javax.swing.JToggleButton EditRecipe;
    private javax.swing.JList Flist;
    private javax.swing.JToggleButton Friday;
    private javax.swing.JButton Friday1;
    private javax.swing.JRadioButton IngredientC;
    private javax.swing.JRadioButton Ingredients;
    private javax.swing.JList Inlist;
    private javax.swing.JTextArea Instructions;
    private javax.swing.JToggleButton Monday;
    private javax.swing.JButton Monday1;
    private javax.swing.JList Rlist;
    private javax.swing.JTextField Rname;
    private javax.swing.JToggleButton Saturday;
    private javax.swing.JButton Saturday1;
    private javax.swing.JButton SearchR;
    private javax.swing.JButton SearchR1;
    private javax.swing.JButton SearchR2;
    private javax.swing.JToggleButton Sunday;
    private javax.swing.JButton Sunday1;
    private javax.swing.JToggleButton Thursday;
    private javax.swing.JButton Thursday1;
    private javax.swing.JToggleButton Tuesday;
    private javax.swing.JButton Tuesday1;
    private javax.swing.JButton Update;
    private javax.swing.JToggleButton Wednesday;
    private javax.swing.JButton Wednesday1;
    private javax.swing.JButton addF;
    private javax.swing.JButton addR;
    private javax.swing.JToggleButton breakfast;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JPanel cookbook;
    private javax.swing.JList curFood;
    private javax.swing.JToggleButton dnd;
    private javax.swing.JTextPane foodFacts;
    private javax.swing.JTextPane foodInfo;
    private javax.swing.JList foodlist1;
    private javax.swing.JList foodneeded;
    private javax.swing.JPanel fridge;
    private javax.swing.JPanel home;
    private javax.swing.JTextPane ingredients;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane12;
    private javax.swing.JScrollPane jScrollPane13;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JScrollPane jScrollPane15;
    private javax.swing.JScrollPane jScrollPane16;
    private javax.swing.JScrollPane jScrollPane17;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JScrollPane jScrollPane19;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane20;
    private javax.swing.JScrollPane jScrollPane21;
    private javax.swing.JScrollPane jScrollPane22;
    private javax.swing.JScrollPane jScrollPane23;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JList listCategory;
    private javax.swing.JList listingredient;
    private javax.swing.JToggleButton lunch;
    private javax.swing.JPanel mealPlan;
    private javax.swing.JList mealsB;
    private javax.swing.JList mealsB1;
    private javax.swing.JList mealsD;
    private javax.swing.JList mealsD1;
    private javax.swing.JList mealsL;
    private javax.swing.JList mealsL1;
    private javax.swing.JList recList;
    private javax.swing.JButton removeF;
    private javax.swing.JButton removeR;
    private javax.swing.JList searchList;
    private javax.swing.JList searchList1;
    private javax.swing.JList searchList2;
    private javax.swing.JPanel shopList;
    private javax.swing.JLabel title;
    private javax.swing.JList weekList;
    // End of variables declaration//GEN-END:variables
}

